# 2.行列積

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# 問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。
計算過程もマークダウンテキストを用いて説明してください。

In [ ]:
AB = [[ (-1*0) + 2*0 + 3*2  (-1*2 ) + 2*2 + 3*9  (-1*1) + 2*(-8) + 3*(-1)
            (4*0) + (-5*0) + 6*2  4*2 + (-5*2) + 6*9  4*1 + (-5)*(-8) + 6*(-1)
              7*0 + 8*0 + (-9*2)  7*2 + 8*2 + (-9* 9)  7*1 + 8*(-8) + (-9)*(-1)]]

説明　行列Aの1行目と行列Bの１行目を組み合わせて計算　→　(1, 1)成分
　　　行列Aの1行目と行列Bの 2行目を組み合わせて計算　→　(1, 2)成分
   　　行列Aの1行目と行列Bの 3行目を組み合わせて計算　→　(1, 3)成分
  　    行列Aの2行目と行列Bの 1行目を組み合わせて計算　→　(2, 1)成分
         行列Aの2行目と行列Bの 2行目を組み合わせて計算　→　(2, 2)成分
         行列Aの2行目と行列Bの 3行目を組み合わせて計算　→　(2, 3)成分
         行列Aの3行目と行列Bの１行目を組み合わせて計算　→　(3, 1)成分
         行列Aの3行目と行列Bの 2行目を組み合わせて計算　→　(3, 2)成分
         行列Aの3行目と行列Bの 3行目を組み合わせて計算　→　(3, 3)成分

In [ ]:
       =[[ (0 + 0 + 6)  (-2 + 4 + 27)  (-1 + (-16) + (-3))
         (0 + 0 + 12)  (8 + (-10) + 54)  (4 + 40 + (-6))  
         (0 + 0 + (-18))  (14 + 16 + (-81)  7 + (-64) + 9)]]

In [ ]:
   = [[6 29 -20
        12 52 38
        -18 -51 -48]]

# 【問題2】NumPyの関数による計算

この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。
これらを使い行列積を計算してください

In [ ]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [9]:
# np.matmul()
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [10]:
# np.dot()
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [11]:
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 【問題3】ある要素の計算を実装

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [145]:
K=3
matrix1 = np.random.randint(1,10,(1,K)) # 任意の範囲の整数
matrix2 = np.random.randint(1,10,(K,1))
print(matrix1)
print(matrix2)
print(matrix1.shape[0])
dst0 = np.zeros((matrix1.shape[0],matrix2.shape[0]), dtype=matrix1.dtype) #空の行列作成
print(dst0)

for i in range(matrix1.shape[0]): #matrix1.shape[0]=1 range(1)  i=0
    for k in range(matrix2.shape[0]): # matrix2.shape[0]=3  range(3) k=0,1,2 
        dst0[i, k] = dst0[i, k] + matrix1[i, k] * matrix2[k, i]
print(dst0)

[[6 9 8]]
[[4]
 [7]
 [1]]
1
[[0 0 0]]
[[24 63  8]]


# 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


In [273]:
def matrix_multiplication(mat1,mat2):
    dst1 = np.zeros((mat1.shape[0], mat2.shape[1]), dtype=mat1.dtype) #空の行列を作っておく　dtype=mat1.dtypeをつける意味？

    for i in range(mat1.shape[0]): #0 1  shape[0] は行 2  mat2.shape[1]は 列２
        for j in range(mat2.shape[1]): #0 1
            for k in range(mat1.shape[1]): #0 1
                dst1[i, j] = dst1[i, j] + mat1[i, k] * mat2[k, j] # 多重ループ　空に入れていく
    return dst1


mat1 = np.random.randint(1, 10, (3, 3))
mat2 = np.random.randint(1, 10, (3, 3))

print('mat1', mat1)
print('mat2', mat2)

x =matrix_multiplication(mat1,mat2)
print('dst1', x)

# numpy を利用した行列積
dst2 = np.matmul(mat1, mat2)
print('dst2', dst2)



mat1 [[2 3 2]
 [9 1 3]
 [2 7 1]]
mat2 [[1 2 9]
 [3 7 6]
 [1 3 5]]
dst1 [[ 13  31  46]
 [ 15  34 102]
 [ 24  56  65]]
dst2 [[ 13  31  46]
 [ 15  34 102]
 [ 24  56  65]]


# 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。


In [248]:
def matrix_multiplication(mat1,mat2):
    if x== y: 
        dst1 = np.zeros((mat1.shape[0], mat2.shape[1]), dtype=mat1.dtype)
        for i in range(mat1.shape[0]):
            for j in range(mat2.shape[1]): 
                 for k in range(mat1.shape[1]): 
                    dst1[i, j] = dst1[i, j] + mat1[i, k] * mat2[k, j] 
        return dst1
    else: 
          print('エラー: 行列mat1 の2次元目の要素数と行列mat2の1次元目の要素数が異なるため計算終了')
            
# 行列mat1 の2次元目の要素数 x         
x=1 
# 行列mat2の1次元目の要素数 y
y=3
            
mat1 = np.random.randint(1, 10, (3, x))
mat2 = np.random.randint(1, 10, (y, 3))

print('mat1', mat1)
print('mat2', mat2)

z =matrix_multiplication(mat1,mat2)
print('dst1', z)


mat1 [[2]
 [9]
 [5]]
mat2 [[4 1 7]
 [9 6 9]
 [6 1 2]]
エラー: 行列mat1 の2次元目の要素数と行列mat2の1次元目の要素数が異なるため計算終了
dst1 None


# 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [274]:
def matrix_multiplication(mat1,mat2):
    if x== y: 
        dst1 = np.zeros((mat1.shape[0], mat2.shape[1]), dtype=mat1.dtype)
        for i in range(mat1.shape[0]):
            for j in range(mat2.shape[1]): 
                 for k in range(mat1.shape[1]): 
                    dst1[i, j] = dst1[i, j] + mat1[i, k] * mat2[k, j] 
        return dst1
    else:
        mat2 = np.transpose(mat2) #ここで転置
        dst1 = np.zeros((mat1.shape[0], mat2.shape[1]), dtype=mat1.dtype)
        for i in range(mat1.shape[0]):
            for j in range(mat2.shape[1]): 
                 for k in range(mat1.shape[1]): 
                    dst1[i, j] = dst1[i, j] + mat1[i, k] * mat2[k, j] 
        return dst1
        #print('エラー: 行列mat1 の2次元目の要素数と行列mat2の1次元目の要素数が異なるため計算終了')
            
# 行列mat1,行列mat2 の2次元目の要素数 x         
x=4
# 行列mat1,行列mat2の1次元目の要素数 y
y=2
            
mat1 = np.random.randint(1, 10, (y, x))
mat2 = np.random.randint(1, 10, (y, x))

print('mat1', mat1)
print('mat2', mat2)

z =matrix_multiplication(mat1,mat2)
print('dst1', z)


mat1 [[6 7 4 5]
 [3 9 4 1]]
mat2 [[2 1 2 4]
 [6 6 5 5]]
dst1 [[ 47 123]
 [ 27  97]]
