# week4授業前課題3 オブジェクト指向の活用

### インスタンス化
クラスを使う際はまず以下のようなコードを書きますが、これを インスタンス化 と呼びます。

scaler = StandardScaler()

StandardScalerというクラスオブジェクトから、scalerと名前をつけたインスタンスオブジェクトが作られました。

《クラスの命名法》

Pythonではクラス名は頭文字が大文字、他は小文字という命名法がPEP8により定められています。単語間にアンダースコアは入れません。これを CapWords 方式と呼びます。
こういった形式のものはクラスだと判断することができます。

《インスタンスは複数作れる》

あるクラスオブジェクトからは複数のインスタンスオブジェクトを作成することが可能です。

# 【問題1】これまで利用してきたクラスの列挙


クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。

Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

Pandas : pdDataFrame
matplotlib : matplotlib.figure.Figure
scikit-learn : LinearRegression()  SVR() RandomForestRegressor()

インスタンス化を行った後には、scaler.fit(X)のような メソッド の実行ができます。StandardScalerのfitメソッドは後でスケーリングに使われる平均と標準偏差を計算する機能があります。

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

In [ ]:
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。

最低でもそれぞれ5つ以上答えてください。

In [ ]:
:plt.show() メソッド
:plt.xlabel() メソッド
:plt.scatter() メソッド
:linear_reg.predict() メソッド
:linear_reg.fit() メソッド
:.dtypes インスタンス変数

# 【問題3】標準化クラスをスクラッチで作成

理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。

今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。

インスタンス変数を作成する際はself.mean_のようにselfを付けます。クラスの外からscaler.mean_と書いていたscalerの部分が自分自身を表すselfになっています。

In [5]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """

        self.mean_ = X.mean(axis=0)
        self.var_ = X.var(axis=0)

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X-self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [6]:
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


# 【問題4】 四則演算を行うクラスの作成

上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。

コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。

クラス名や説明文も適切に書き換えてください。

In [12]:
class ExampleClass():
    
    def __init__(self, value):
        assert type(value) in [int,float], "ooooooooooo"
        self.value = value
        print("初期値{}が設定".format(self.value))
    
    def add (self, value2):
        self.value += value2
    
    def sub(self,value2):
        self.value -= value2
    
    def mul(self,value2):
        self.value *= value2
        
    def div(self,value2):
        self.value /= value2
        


In [13]:
example = ExampleClass(10)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.sub(1)
print("value : {}".format(example.value))
example.mul(4)
print("value : {}".format(example.value))
example.div(2)
print("value : {}".format(example.value))

初期値10が設定
value : 10
value : 13
value : 12
value : 48
value : 24.0


In [14]:
# floatを入力
example = ExampleClass(5.0)
print("value : {}".format(example.value))

初期値5.0が設定
value : 5.0


In [15]:
# strを入力→数値以外はエラーになる事を確認
example = ExampleClass("5")
print("value : {}".format(example.value))

AssertionError: ooooooooooo